### PR TITLE
External Datasource for AKS Private DNS Name

### PR DESCRIPTION
**Pull request by mathieu-benoit**
- Use the `azurerm_private_dns_zone_virtual_network_link` resource + explicit dependencies on the `azurerm_kubernetes_cluster.k8s.node_resource_group` value.
- Use the `external` provider to get the AKS Private DNS name (advantage of just a get/read external script)

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
Ready for your review and your integration if you are interested by this ;)

**Review by feiskyer — COMMENTED** [review]
this is cool, thanks

**Comment by feiskyer** [comment]
@mathieu-benoit I tried this way today, and it doesn't work for me now. The original scripts still works.  Have you tried it these days?

**Comment by mathieu-benoit** [comment]
Oh ok, what's the issue? I will run it later today to check.

**Comment by feiskyer** [comment]
@mathieu-benoit the private cluster creation failed because private dns zone not linked. I reverted this commit as a workaround in my tests.

**Pull request merged**
